# Generated by Django 5.2.12 on 2026-03-11 16:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('address', models.TextField()),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Locker',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('local_id', models.TextField()),
                ('size', models.TextField()),
                ('status', models.TextField()),
                ('type', models.TextField()),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('passcode', models.TextField()),
                ('qr_data', models.TextField()),
                ('is_door_open', models.BooleanField(default=False)),
                ('has_object', models.BooleanField(default=False)),
                ('is_locked', models.BooleanField(default=True)),
                ('deposit_start_time', models.BigIntegerField(blank=True, null=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lockers', to='foodlocker.building')),
            ],
        ),
        migrations.CreateModel(
            name='LockerLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.TextField()),
                ('actor_id', models.TextField()),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('locker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='foodlocker.locker')),
            ],
        ),
        migrations.CreateModel(
            name='LineUser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('line_user_id', models.TextField(unique=True)),
                ('room_no', models.TextField()),
                ('display_name', models.TextField()),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_users', to='foodlocker.building')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_users', to='foodlocker.project')),
            ],
        ),
        migrations.AddField(
            model_name='building',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='foodlocker.project'),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unit_number', models.TextField()),
                ('floor', models.TextField()),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='foodlocker.building')),
            ],
        ),
    ]
