# Generated by Django 5.2.12 on 2026-05-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodlocker", "0002_alter_locker_status"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="locker",
            index=models.Index(
                fields=["building", "status", "type", "size"], name="locker_lookup_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="locker",
            index=models.Index(
                fields=["status", "qr_data"], name="locker_qr_lookup_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="locker",
            index=models.Index(
                fields=["status", "passcode"], name="locker_pin_lookup_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="locker",
            index=models.Index(
                fields=["building", "local_id"], name="locker_wall_order_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lockerlog",
            index=models.Index(
                fields=["actor_id", "locker"], name="lockerlog_actor_locker_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lockerlog",
            index=models.Index(
                fields=["locker", "-created_at"], name="lockerlog_locker_created_idx"
            ),
        ),
    ]
